server:
  port: 8989
  servlet:
    jsp:
      init-parameters:
        development: true #开启jsp热部署
#  spring.servlet.multipart.enabled = true
#  # Single file max size  即单个文件大小
#  spring.servlet.multipart.max-file-size = 5Mb
#  # All files max size      即总上传的数据大小
#  spring.servlet.multipart.max-request-size = 100Mb

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testems
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 1024Mb


mybatis-plus:
  mapper-locations: classpath:com/rh/mapper/*.xml  #指定mapper配置文件位置
  type-aliases-package: com.baizhi.entity              #指定起别名来的类


